<?php
/**
 * @file
 * Code for the Panopoly Event feature.
 */

include_once 'panopoly_event.features.inc';

/**
 * @file
 * Code for the Panopoly Event feature.
 */
function panopoly_event_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

function panopoly_event_ctools_render_alter(&$info, &$page, &$context) {
  if(isset($context['handler']) && is_object($context['handler'])) {
    $handler = $context['handler'];
    if(property_exists($handler, 'name') && $handler->name == 'node_edit_panel_context') {
      ctools_add_css('date_tweaks', 'panopoly_event', 'inc/css');
    }

  }
}
